In [1]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn import preprocessing
import numpy as np
import time
from sklearn.metrics import accuracy_score
from sklearn import cross_validation
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier

In [3]:
def time_transform(x):
    if x >= 1000:
        x=0

In [32]:
database.groupby("g5").size()

g5
0     364
1      80
2      92
3     144
4      10
5     196
6      55
7      44
8     305
9      55
10     70
11     46
12     67
13    190
14     34
15     49
16     19
dtype: int64

In [33]:
database.describe()

,dx,dy,g1,t1,vx1,vy1,g2,t2,vx2,vy2,...,vx3,vy3,g4,t4,vx4,vy4,g5,t5,vx5,vy5
count,1820.000000,1820,1820.000000,1820,1820.000000,1820,1820.000000,1820,1820.000000,1820,...,1820.000000,1820,1820.000000,1820,1820.000000,1820,1820.000000,1820,1820.000000,1820
mean,2.343752,0,7.730220,0,0.186537,0,7.342308,0,0.187368,0,...,0.183327,0,6.571429,0,0.179910,0,6.200000,0,0.176263,0
std,0.892665,0,4.035204,0,0.734500,0,4.317762,0,0.731028,0,...,0.724893,0,4.671726,0,0.719756,0,4.795499,0,0.711420,0
min,0.000000,0,1.000000,0,-2.700677,0,0.000000,0,-2.700677,0,...,-2.700677,0,0.000000,0,-2.700677,0,0.000000,0,-2.700677,0
25%,1.632121,0,5.000000,0,-0.021213,0,3.000000,0,-0.018580,0,...,-0.014960,0,2.000000,0,-0.011314,0,2.000000,0,-0.010198,0
50%,1.980591,0,8.000000,0,-0.000209,0,8.000000,0,-0.000048,0,...,0.000000,0,7.000000,0,0.000000,0,6.000000,0,0.000000,0
75%,2.871147,0,11.000000,0,0.020388,0,11.000000,0,0.017007,0,...,0.013328,0,10.000000,0,0.010845,0,10.000000,0,0.007419,0
max,4.502469,0,16.000000,0,4.413043,0,16.000000,0,4.413043,0,...,4.413043,0,16.000000,0,4.413043,0,16.000000,0,4.413043,0

In [10]:
database = pd.read_csv("/home/jmirandadealme/Documents/SistAut/HumanRobotInteraction/others/TrainingData/todos.txt",
                      quotechar ="'")



#database["t5"] = 0
#database["t4"] = 0
#database["t3"] = 0
#database["t2"] = 0
#database["t1"] = 0




le = preprocessing.LabelEncoder()
le.fit(['0.0','closingforearm','armmovingdown','armmovingup',
        'armstopped','forearmstopped','handaboveelbow','handunderelbow',
        'openingforearm','walkingbackward','walkingforward','waving','nowalking',
        'calling', 'handing','elbowbehindbody','elbowinfrontofbody'])
database["g1"]=le.transform(database["g1"])
database["g2"]=le.transform(database["g2"])
database["g3"]=le.transform(database["g3"])
database["g4"]=le.transform(database["g4"])
database["g5"]=le.transform(database["g5"])

labels = database['label'].values

database.drop("label",axis=1,inplace=True)

database.head()

,dx,dy,g1,t1,vx1,vy1,g2,t2,vx2,vy2,...,vx3,vy3,g4,t4,vx4,vy4,g5,t5,vx5,vy5
0,4.404114,0,1,1.448972e+09,4.404114,0,0,1.448972e+09,0.000000,0,...,0.000000,0,0,-1.448972e+09,0.000000,0,0,-1.448972e+09,0.000000,0
1,4.404114,0,5,1.448972e+09,4.404114,0,1,0.000000e+00,4.404114,0,...,0.000000,0,0,-1.448972e+09,0.000000,0,0,-1.448972e+09,0.000000,0
2,4.392251,0,3,1.448972e+09,-0.011864,0,5,1.000001e-01,4.404114,0,...,4.404114,0,0,1.448972e+09,0.000000,0,0,-1.448972e+09,0.000000,0
3,4.392251,0,8,1.448972e+09,-0.011864,0,3,0.000000e+00,-0.011864,0,...,4.404114,0,1,-1.000001e-01,4.404114,0,0,1.448972e+09,0.000000,0
4,4.364057,0,13,1.448972e+09,-0.028194,0,8,2.000000e-01,-0.011864,0,...,-0.011864,0,5,-9.999990e-02,4.404114,0,1,-3.000002e-01,4.404114,0

In [17]:
database = pd.read_csv("/home/jmirandadealme/Documents/SistAut/HumanRobotInteraction/others/TrainingData/todos2.txt",
                      quotechar ="'")



labels = database['label'].values

database.drop("label",axis=1,inplace=True)

database.head()

,dx,dy,g1,t1,vx1,vy1,g2,t2,vx2,vy2,...,vx3,vy3,g4,t4,vx4,vy4,g5,t5,vx5,vy5
0,4.4041,0,6,0,4.404100,0,0,0.0,0.000000,0,...,0.000000,0,0,0.0,0.0000,0,0,0.0,0.0000,0
1,4.4041,0,1,0,4.404100,0,6,0.0,4.404100,0,...,0.000000,0,0,0.0,0.0000,0,0,0.0,0.0000,0
2,4.3923,0,5,0,-0.011864,0,1,0.1,4.404100,0,...,4.404100,0,0,0.0,0.0000,0,0,0.0,0.0000,0
3,4.3923,0,4,0,-0.011864,0,5,0.0,-0.011864,0,...,4.404100,0,6,-0.1,4.4041,0,0,0.0,0.0000,0
4,4.3641,0,7,0,-0.028194,0,4,0.2,-0.011864,0,...,-0.011864,0,1,-0.1,4.4041,0,6,-0.3,4.4041,0

In [12]:
features = database.values

pca = PCA(n_components =17)
pca.fit(features)
features = pca.transform(features)
print(pca.explained_variance_ratio_)

ValueError: n_components=50 invalid for n_features=22

In [14]:
# TRAIN SVM


classf = SVC()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.32864689827 seconds ---

In [42]:
# TRAIN LinearSVC


classf = LinearSVC()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.801818847656 seconds ---

In [44]:
# TRAIN LogisticRegression

classf = LogisticRegression()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.0455949306488 seconds ---

In [53]:
# TRAIN 3NN

classf = KNeighborsClassifier(n_neighbors=5)
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.00180292129517 seconds ---

In [48]:

# TRAIN AdaBoostClassifier

classf = AdaBoostClassifier()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.232806921005 seconds ---

In [50]:
# Train SGDClassifier

classf = SGDClassifier()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.00567102432251 seconds ---

In [16]:
# Predict

start_time = time.time()
predict_labels=classf.predict(features)
print("--- %s seconds ---" % (time.time() - start_time))
score = accuracy_score(labels,predict_labels)
print("Accuracy: %0.2f" % (score))
# Cross Validation
start_time = time.time()
scores = cross_validation.cross_val_score(classf, features, labels, cv=10)
print("--- %s seconds ---" % (time.time() - start_time))
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

--- 0.213733911514 seconds ---
Accuracy: 0.73
--- 2.76780200005 seconds ---
Accuracy: 0.62 (+/- 0.13)

In [52]:
database = pd.read_csv("/home/jmirandadealme/Documents/SistAut/HumanRobotInteraction/others/TrainingData/todos2.txt",
                      quotechar ="'")



labels = database['label'].values

database.drop("label",axis=1,inplace=True)

database.head()

,dx,dy,g1,t1,vx1,vy1,g2,t2,vx2,vy2,...,vx3,vy3,g4,t4,vx4,vy4,g5,t5,vx5,vy5
0,4.4041,0,6,0,4.404100,0,0,0.0,0.000000,0,...,0.000000,0,0,0.0,0.0000,0,0,0.0,0.0000,0
1,4.4041,0,1,0,4.404100,0,6,0.0,4.404100,0,...,0.000000,0,0,0.0,0.0000,0,0,0.0,0.0000,0
2,4.3923,0,5,0,-0.011864,0,1,0.1,4.404100,0,...,4.404100,0,0,0.0,0.0000,0,0,0.0,0.0000,0
3,4.3923,0,4,0,-0.011864,0,5,0.0,-0.011864,0,...,4.404100,0,6,-0.1,4.4041,0,0,0.0,0.0000,0
4,4.3641,0,7,0,-0.028194,0,4,0.2,-0.011864,0,...,-0.011864,0,1,-0.1,4.4041,0,6,-0.3,4.4041,0