In [84]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn import preprocessing
import numpy as np
import time
from sklearn.metrics import accuracy_score
from sklearn import cross_validation
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier

In [32]:
database.groupby("g5").size()

g5
0     364
1      80
2      92
3     144
4      10
5     196
6      55
7      44
8     305
9      55
10     70
11     46
12     67
13    190
14     34
15     49
16     19
dtype: int64

In [33]:
database.describe()

,dx,dy,g1,t1,vx1,vy1,g2,t2,vx2,vy2,...,vx3,vy3,g4,t4,vx4,vy4,g5,t5,vx5,vy5
count,1820.000000,1820,1820.000000,1820,1820.000000,1820,1820.000000,1820,1820.000000,1820,...,1820.000000,1820,1820.000000,1820,1820.000000,1820,1820.000000,1820,1820.000000,1820
mean,2.343752,0,7.730220,0,0.186537,0,7.342308,0,0.187368,0,...,0.183327,0,6.571429,0,0.179910,0,6.200000,0,0.176263,0
std,0.892665,0,4.035204,0,0.734500,0,4.317762,0,0.731028,0,...,0.724893,0,4.671726,0,0.719756,0,4.795499,0,0.711420,0
min,0.000000,0,1.000000,0,-2.700677,0,0.000000,0,-2.700677,0,...,-2.700677,0,0.000000,0,-2.700677,0,0.000000,0,-2.700677,0
25%,1.632121,0,5.000000,0,-0.021213,0,3.000000,0,-0.018580,0,...,-0.014960,0,2.000000,0,-0.011314,0,2.000000,0,-0.010198,0
50%,1.980591,0,8.000000,0,-0.000209,0,8.000000,0,-0.000048,0,...,0.000000,0,7.000000,0,0.000000,0,6.000000,0,0.000000,0
75%,2.871147,0,11.000000,0,0.020388,0,11.000000,0,0.017007,0,...,0.013328,0,10.000000,0,0.010845,0,10.000000,0,0.007419,0
max,4.502469,0,16.000000,0,4.413043,0,16.000000,0,4.413043,0,...,4.413043,0,16.000000,0,4.413043,0,16.000000,0,4.413043,0

In [85]:
database = pd.read_csv("/home/jmirandadealme/Documents/SistAut/HumanRobotInteraction/others/TrainingData/todos.txt",
                      quotechar ="'")



database["t5"] = 0
database["t4"] = 0
database["t3"] = 0
database["t2"] = 0
database["t1"] = 0




le = preprocessing.LabelEncoder()
le.fit(['0.0','closingforearm','armmovingdown','armmovingup',
        'armstopped','forearmstopped','handaboveelbow','handunderelbow',
        'openingforearm','walkingbackward','walkingforward','waving','nowalking',
        'calling', 'handing','elbowbehindbody','elbowinfrontofbody'])
database["g1"]=le.transform(database["g1"])
database["g2"]=le.transform(database["g2"])
database["g3"]=le.transform(database["g3"])
database["g4"]=le.transform(database["g4"])
database["g5"]=le.transform(database["g5"])

labels = database['label'].values

database.drop("label",axis=1,inplace=True)

database.head()

,dx,dy,g1,t1,vx1,vy1,g2,t2,vx2,vy2,...,vx3,vy3,g4,t4,vx4,vy4,g5,t5,vx5,vy5
0,4.404114,0,1,0,4.404114,0,0,0,0.000000,0,...,0.000000,0,0,0,0.000000,0,0,0,0.000000,0
1,4.404114,0,5,0,4.404114,0,1,0,4.404114,0,...,0.000000,0,0,0,0.000000,0,0,0,0.000000,0
2,4.392251,0,3,0,-0.011864,0,5,0,4.404114,0,...,4.404114,0,0,0,0.000000,0,0,0,0.000000,0
3,4.392251,0,8,0,-0.011864,0,3,0,-0.011864,0,...,4.404114,0,1,0,4.404114,0,0,0,0.000000,0
4,4.364057,0,13,0,-0.028194,0,8,0,-0.011864,0,...,-0.011864,0,5,0,4.404114,0,1,0,4.404114,0

In [88]:
features = database.values

pca = PCA(n_components =15)
pca.fit(features)
features = pca.transform(features)
print(pca.explained_variance_ratio_)

[  3.46872822e-01   1.66355287e-01   1.57703671e-01   1.53268090e-01
   1.46422486e-01   8.94395194e-03   6.60509903e-03   4.98056494e-03
   3.71252109e-03   2.84668505e-03   2.28882342e-03   3.81755748e-33
   4.87750187e-34   1.62553594e-34   7.58810456e-35]

In [60]:
# TRAIN SVM


classf = SVC()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.357744932175 seconds ---

In [66]:
# TRAIN LinearSVC


classf = LinearSVC()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))

--- 1.11276507378 seconds ---

In [57]:
# TRAIN LogisticRegression

classf = LogisticRegression()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.056391954422 seconds ---

In [80]:
# TRAIN 3NN

classf = KNeighborsClassifier(n_neighbors=3)
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.00203919410706 seconds ---

In [69]:

# TRAIN AdaBoostClassifier

classf = AdaBoostClassifier()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.286468029022 seconds ---

In [89]:
# Train SGDClassifier

classf = SGDClassifier()
start_time = time.time()
classf.fit(features,labels)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.00660610198975 seconds ---

In [90]:
# Predict

start_time = time.time()
predict_labels=classf.predict(features)
print("--- %s seconds ---" % (time.time() - start_time))
score = accuracy_score(labels,predict_labels)
print("Accuracy: %0.2f" % (score))
# Cross Validation
start_time = time.time()
scores = cross_validation.cross_val_score(classf, features, labels, cv=10)
print("--- %s seconds ---" % (time.time() - start_time))
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

--- 0.000741958618164 seconds ---
Accuracy: 0.42
--- 0.0790998935699 seconds ---
Accuracy: 0.40 (+/- 0.10)

In [9]:
database = pd.read_csv("/home/jmirandadealme/Documents/SistAut/HumanRobotInteraction/others/TrainingData/todos.txt",
                       quotechar ="'")



database["t5"] = 0
database["t4"] = 0
database["t3"] = 0
database["t2"] = 0
database["t1"] = 0

database.describe()

,dx,dy,t1,vx1,vy1,t2,vx2,vy2,t3,vx3,vy3,t4,vx4,vy4,t5,vx5,vy5,label
count,1820.000000,1820,1.820000e+03,1820.000000,1820,1.820000e+03,1820.000000,1820,1.820000e+03,1820.000000,1820,1.820000e+03,1820.000000,1820,1.820000e+03,1820.000000,1820,1820.000000
mean,2.343752,0,1.448979e+09,0.186537,0,7.324509e+07,0.187368,0,-1.005055e-02,0.183327,0,-7.404123e+07,0.179910,0,-1.480825e+08,0.176263,0,3.429670
std,0.892665,0,2.956976e+03,0.734500,0,3.175235e+08,0.731028,0,4.608447e+08,0.724893,0,5.585047e+08,0.719756,0,6.310296e+08,0.711420,0,1.816787
min,0.000000,0,1.448972e+09,-2.700677,0,0.000000e+00,-2.700677,0,-1.448981e+09,-2.700677,0,-1.448981e+09,-2.700677,0,-1.448981e+09,-2.700677,0,1.000000
25%,1.632121,0,1.448979e+09,-0.021213,0,9.999275e-04,-0.018580,0,-1.000001e-01,-0.014960,0,-3.000002e-01,-0.011314,0,-6.029998e-01,-0.010198,0,2.000000
50%,1.980591,0,1.448980e+09,-0.000209,0,9.999990e-02,-0.000048,0,0.000000e+00,0.000000,0,-1.010001e-01,0.000000,0,-2.049999e-01,0.000000,0,4.000000
75%,2.871147,0,1.448981e+09,0.020388,0,2.000000e-01,0.017007,0,1.000001e-01,0.013328,0,5.960464e-08,0.010845,0,-9.700012e-02,0.007419,0,5.000000
max,4.502469,0,1.448981e+09,4.413043,0,1.448981e+09,4.413043,0,1.448981e+09,4.413043,0,1.448981e+09,4.413043,0,1.448981e+09,4.413043,0,7.000000